FROM --platform=linux/amd64 node:18.18.0-alpine AS build

ARG REACT_APP_API_PATH

ENV REACT_APP_API_PATH $REACT_APP_API_PATH

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . .

CMD ["npm", "run", "start"]
