export type ProjectsType = {
    id: string,
    title: string,
    summary: string,
    description: string,
    logo: string,
    geoCoordinates: string,
    creationDate: string,
    status: string,
    ownerSum: number,
    collectedSum: number,
    startSum: number,
    collectDeadline: string,
    goalSum: number,
    goalDeadline: string,
};
